spring:
  application:
    name: ai-agent
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${deepseek-api}
      model-name: deepseek-chat
    embedding-model:
      base-url: https://aihubmix.com/v1
      api-key: sk-7FSC8rpCuanVrFgMAbC4882fB993417aB0B9Aa346417A451
    streaming-chat-model:
      api-key: ${deepseek-api}
      model-name: deepseek-chat
      base-url: https://api.deepseek.com

pinecone:
  api:
    key: ${pinecone-api}
  index:
    name: agent-index



