spring:
  application:
    name: ai-agent
  datasource:
    url: jdbc:mysql://localhost:3306/ai_agent?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai
    username: root
    password: kx6855253
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${deepseek-api}
      model-name: deepseek-chat
    embedding-model:
      base-url: https://aihubmix.com/v1
      api-key: sk-7FSC8rpCuanVrFgMAbC4882fB993417aB0B9Aa346417A451
    streaming-chat-model:
      api-key: ${deepseek-api}
      model-name: deepseek-chat
      base-url: https://api.deepseek.com

pinecone:
  api:
    key: ${pinecone-api}
  index:
    name: agent-index

feishu:
  app-id: cli_a94deb3b6cf89cce
  app-secret: ZEFUg3I3OowRGZBvnXJobgMWQnavzNlV

scheduler:
  reminder:
    fixed-delay-ms: 60000



